### ISSUE TITLE
Typescript 支持

### ISSUE THREAD

**Issue by forthedamn** [meituan/beeshell#1]
请问有计划提供 Typescript 类型支持吗

**Comment by wxlworkhard** [comment]
暂时没有，我们还是推荐使用 ES6

**Comment by mactive** [comment]
目前大部分组件都有严格的PropTypes 定义, 可以保证使用上的严谨性. 
会尽快提供 index.d.ts 文件的. 让你有更好的  intelligentize Input

**Comment by Kennytian** [comment]
太好了，有d.ts也行

**Comment by jamninetyfive** [comment]
在每个开源下面看到最多的就是 开源支持我们邪教TS吗？

**Comment by jamninetyfive** [comment]
每个开源下面看到最多的就是 求支持我们邪教TS
