### ISSUE TITLE
建议Button组件自定义的样式能够生效，查看源码得到的结论是不生效的

### ISSUE THREAD

**Issue by ch957869975** [meituan/beeshell#10]
### 问题是什么
问题的具体描述，尽量详细

### 环境
- 手机: iPhone 8
- 系统：iOS 11.2
- beeshell版本：1.0.1
- 其他版本信息

### 在线例子
如果有请提供在线例子或代码片段

### 其他
其他信息

**Comment by wxlworkhard** [comment]
@davidleee 是这样的，是为了支持一些外边距，或者定位的相关样式，不想让用户自定义太多样式
