### ISSUE TITLE
表单过长的键盘遮挡问题怎么处理？

### ISSUE THREAD

**Issue by foyel** [meituan/beeshell#11]
### 问题是什么
问题的具体描述，尽量详细

### 环境
- 手机: iPhone 8
- 系统：iOS 11.2
- beeshell版本：1.0.1
- 其他版本信息

### 在线例子
如果有请提供在线例子或代码片段

### 其他
其他信息

**Comment by wxlworkhard** [comment]
不太清楚你的问题

**Comment by XHL-Mao** [comment]
是指键盘遮挡了输入框？想要自动弹起？ iOS可以引入IQKeyboardManager  (简单点)
