### ISSUE TITLE
什么时候会加入进度条或者进度弹窗呢

### ISSUE THREAD

**Issue by lanwufeng** [meituan/beeshell#14]
### 问题是什么
问题的具体描述，尽量详细

### 环境
- 手机: iPhone 8
- 系统：iOS 11.2
- beeshell版本：1.0.1
- 其他版本信息

### 在线例子
如果有请提供在线例子或代码片段

### 其他
其他信息

**Comment by wxlworkhard** [comment]
下一版本支持进度条组件
