### ISSUE TITLE
在 react 中使用报错.

### ISSUE THREAD

**Issue by pheromone** [meituan/beeshell#19]
### 问题是什么
问题的具体描述，尽量详细
我打算在h5 app中使用该库的多级联动,使用的是react
### 环境
- 平台 :  react app 
- beeshell版本：^1.0.1
- 其他版本信息

### 在线例子
如果有请提供在线例子或代码片段
步骤:   1. npm  install beeshell --save
            2. 引入  import { Cascader } from "beeshell";
           npm start报错:
You may need an appropriate loader to handle this file type.

![image](https://user-images.githubusercontent.com/14305431/48248896-149bfe80-e434-11e8-8d44-a6fc2ec23416.png)

### 其他
其他信息

**Comment by wxlworkhard** [comment]
这是 RN 组件库，不是 Web 端的

**Comment by pheromone** [comment]
@wxlworkhard  谢谢,我以为都可以呢
