### ISSUE TITLE
长列表数据量大的时候还是卡有白屏的现象，建议直接封个原生的

### ISSUE THREAD

**Issue by minicase** [meituan/beeshell#23]
### 问题是什么
长列表数据量大的时候还是卡有白屏的现象

### 环境
- 手机: 小米max3
- 系统：安卓 8
- beeshell版本：1.0.1

基于flatlist的长列表数据量大的时候还是卡有白屏的现象，建议直接封个原生的

**Comment by wxlworkhard** [comment]
我们这边暂时没有 native 的同学支持，sorry

**Comment by wxlworkhard** [comment]
如果没有其他问题，我关闭了啊
