### ISSUE TITLE
Cascader组件加载时报错Each child in an array or iterator should have a unique key

### ISSUE THREAD

**Issue by onebean06** [meituan/beeshell#25]
### 问题是什么
问题的具体描述，尽量详细

### 环境
- 手机: iPhone 8
- 系统：iOS 11.2
- beeshell版本：1.0.1
- 其他版本信息

### 在线例子
如果有请提供在线例子或代码片段

### 其他
其他信息

**Comment by onebean06** [comment]
问题是什么

将Cascader放入 SlideModal 下拉显示时，第一次加载正常，再次下拉就会报出上述错误

环境
系统：Android
beeshell版本：1.0.1

在线例子

           <SlideModal ref={(c) => { this.modalCascader = c; }} cancelable={true}  offsetY={140}  
                                 direction={'down'} >
                            <View>
                                <Cascader options={this.state.options}  style={{ height: 300 }} 
                                          structKeys={['name', 'val', 'child']}
                                          itemSelectedStyle={{ color: 'blue', backgroundColor: 'lightyellow' }}
                                    onConfirm={(selectedChain) => this.onCascaderConfirm(selectedChain)}
                                />
                            </View>
               </SlideModal>

其中Cascader的参数与示例中的一致

**Comment by wxlworkhard** [comment]
这个是警告吧，下个版本（3月底）会修复
