### ISSUE TITLE
单选框按钮bug

### ISSUE THREAD

**Issue by yanhaijing** [meituan/beeshell#3]
### 问题是什么
Radio单选框的bug反馈：
1. 文档错误 checkedValues 应该是 checkedValue
2. 当Radio.Item的trueValue为0时会不能识别
3. onChange事件触发时机不正确，render，press，change时都会触发，正确触发时机应该是change时

### 环境
- 手机: iPhone 8
- 系统：iOS 11.2
- beeshell版本：1.0.1

### 在线例子
如果有请提供在线例子或代码片段

### 其他
其他信息

**Comment by wxlworkhard** [comment]
@yanhaijing 我们内部版本已经升级完毕，在测试中，今天晚点升级

**Comment by yanhaijing** [comment]
@wxlworkhard 嗯，我给修了1和2，O(∩_∩)O哈哈~
