### ISSUE TITLE
建议将原生组件独立成package，按需安装

### ISSUE THREAD

**Issue by hstarorg** [meituan/beeshell#4]
### 问题是什么
建议 or 讨论
由于原生组件既有的复杂度，以及维护升级成本，建议将原生组件，独立为单独的package，名称可参考 beeshell-原生组件名称。

优势：
1. 原生组件大都较大，以及有一堆依赖，分包便于无次需求的用户更容易的上手。
2. 原生组件可定制难度大，同类组件较多，便于用户灵活选择
3. 分包之后，可独立升级更新，对用户的影响更小

**Comment by wxlworkhard** [comment]
1. beeshell 的原生组件如果用户要使用，需要自己配置 Pods、Gradle，如果不使用不配置即可，没有学习成本
2. beeshell 原生组件和其他同类组件并不冲突，安装了 beeshell 也不是必须使用 beeshell 的原生组件，用户可以自由选择其他原生组件
3. 分包的话，如果多个包有依赖关系，一次升级可能需要同时发布多个包，管理成本高

**Comment by hstarorg** [comment]
可以采用分包+汇总包的模式。原生组件一般较为复杂。引用多个不用的原生包意义不大。

**Comment by hstarorg** [comment]
没有定论么？
