### ISSUE TITLE
关于接下组件的一个小建议

### ISSUE THREAD

**Issue by Ekhui** [meituan/beeshell#5]
https://static.ession.com/app/7b22ad6207679f842564150a1b659691.mp4

有没有可能出一个类似这种的控件 大概sectionList带头部 内容是可以滑动切换的FlatList这种概念

我自己尝试手动做了一个但是性能很差 也没多的时间去慢慢做了

所以还想请教一下是否有实现方法 谢谢了！

**Comment by z5614036** [comment]
那个mp4的关键 是滚动列表嵌套， 如果只是切换滚动列表， scroll-tab-view 这个组件已经实现了。主要难度就是 先外层列表，然后等到 头部消失 再滚动内部列表。android 不容易实现

**Comment by Ekhui** [comment]
> 那个mp4的关键 是滚动列表嵌套， 如果只是切换滚动列表， scroll-tab-view 这个组件已经实现了。主要难度就是 先外层列表，然后等到 头部消失 再滚动内部列表。android 不容易实现

其实ios头部也有点问题 就算粘滞注了 也有滑动冲突的问题存在

**Comment by Ekhui** [comment]
> 有七八了长列表共存，这种场景得有定制化的优化策略才行吧，把没有激活的长列表内容置为空 View

把没有激活的长列表设成空这个 其实在 scrollable-tab-view里面有一个没有合并的提交实现了 主要是使用后用户体验较差 而且产品经理第一个不同意哈哈哈哈 

问题在无论是用scrollview+flatList /  scroll-tab-view+flatList / flatList+scrollable-tab-view+flatList
都存在多个列表的滑动冲突

**Comment by z5614036** [comment]
你要有耐心，全部用手势识别系统做  这个库 react-native-gesture-handler  ，可以将手指滑动的距离记录下来。

**Comment by Ekhui** [comment]
> 你要有耐心，全部用手势识别系统做 这个库 react-native-gesture-handler ，可以将手指滑动的距离记录下来。

这个问题不在于收拾的问题 在于滑动的响应 

分享我一最开始的例子 一个scrollview包裹一个带有几个flatList的viewpager 一开始你往上拉的手势 响应在scrollview 当我监听到一个滑动距离 比如头部的粘滞距离到了 就关闭scrollview的响应 开启flatList列表的响应 这时候state切换过程需要1秒差不多 意味着用户不能连贯滑动 需要释放手指重新接触屏幕才能滑动flatList

不知道我这么表达能不能理解 总之这个问题不仅仅是手势的问题

**Comment by z5614036** [comment]
<View>
<Flatlist />
</View>
第一个view接管手势，不让flatlist 能识别手势，那就不需要控制flatlist的滚动响应了。 主要就控制最外层View的，什么时候释放手势，什么时候接管

**Comment by z5614036** [comment]
https://github.com/cesardeazevedo/react-native-bottom-sheet-behavior    ,网页最后有一个完整的嵌套滚动demo  只能在android上，你有空测试一下。

**Comment by Ekhui** [comment]
> https://github.com/cesardeazevedo/react-native-bottom-sheet-behavior ,网页最后有一个完整的嵌套滚动demo 只能在android上，你有空测试一下。

测试并修改了一下 还是没办法满足需求 
其实 https://github.com/tibbus/react-native-scrollable-tab-view 这个修改一下满足大部分需求
就是他切换的时候把没有激活的列表置空影响用户体验 不置空又会导致列表高度错乱 不好解决

**Comment by z5614036** [comment]
你可以试一试 react-native-recyclelistview 这个组件库，它能保持上次记录的状态

**Comment by z5614036** [comment]
用变量的形式保存的 只要把变量 保存下来 下次再回去 把变量付值回去 就行

**Comment by z5614036** [comment]
https://github.com/naqvitalha/recyclerlistview-context-preservation-demo这是保存状态的demo

**Comment by LyCharlie** [comment]
@Ekhui  请问你最后是怎么实现的 我也想实现类似的效果 但是效果不好 而且嵌套的FlatList好像性能很差

**Comment by danmingyang** [comment]
解决了吗
